spring.application.name=consumer
server.port=8082
producer.soap.wsdl-url=http://localhost:8080/soap/waybill?wsdl
spring.datasource.url=${CONSUMER_POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=waybill}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${CONSUMER_POSTGRES_USERNAME:postgres}
spring.datasource.password=${CONSUMER_POSTGRES_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=${CONSUMER_LIQUIBASE_POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
spring.liquibase.user=${CONSUMER_POSTGRES_USERNAME:postgres}
spring.liquibase.password=${CONSUMER_POSTGRES_PASSWORD:postgres}
spring.liquibase.liquibase-schema=waybill
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${CONSUMER_POSTGRES_SCHEMA:waybill}
